apiVersion: v1
kind: ReplicationController

metadata:
    name: mongodb
    namespace: db

spec:
    replicas: 1
    selector:
        app: mongodb
    template:
        metadata:
            labels:
                app: mongodb
        spec:
            containers:
            - name: mongodb
              image: img.rubin.me/library/mongodb:3.4.9
              ports:
              - containerPort: 27017

