apiVersion: v1
kind: Service

metadata:
    name: mongodb
    namespace: db

spec:
    type: NodePort
    ports:
      - port: 27017
        targetPort: 27017
        nodePort: 32376
    selector:
        app: mongodb

