apiVersion: v1
kind: ReplicationController

metadata:
    name: tomcat

spec:
    replicas: 1
    selector:
        app: tomcat
    template:
        metadata:
            labels:
                app: tomcat
        spec:
            containers:
            - name: tomcat
              image: img.rulin.me/library/tomcat:8.5.24
              ports:
              - containerPort: 8080

