apiVersion: v1
kind: Service

metadata:
    name: mysql
    namespace: db

spec:
    #type: NodePort
    ports:
      - port: 3306
     #   targetPort: 3306
     #   nodePort: 32377
    selector:
        app: mysql

